version: '3'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - app

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - C:/project MERN/server:/home/node/app
    networks:
      - app

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file: .env.react
    volumes:
      - C:/project MERN/client:/app
    networks:
      - app

networks:
  app:
    driver: bridge




